# The type of span storage backend to use, options are currently [cassandra,elasticsearch,memory]
span-storage.type: cassandra
# Minimal allowed log Level.
log-level: info
# Frequency of service dependency calculations (default 24h0m0s)
dependency-storage.data-frequency: 24h0m0s
# Defines which metrics backend to use for metrics reporting: expvar, prometheus, none (default "prometheus")
metrics-backend: none
# Defines the route of HTTP endpoint for metrics backends that support scraping (default "/metrics")
metrics-http-route: /metrics

collector:
  # The http port for the health check service (default 14269)
  health-check-http-port: 14269
  # The http port for the collector service (default 14268)
  http-port: 14268
  # The tchannel port for the collector service (default 14267)
  port: 14267
  # The http port for the Zipkin collector service e.g. 9411
  zipkin.http-port: 9411
  # The number of workers pulling items from the queue (default 50)
  num-workers: 50
  # The queue size of the collector (default 2000)
  queue-size: 2000
  # The duration to wait before rewriting an existing service or operation name (default 12h0m0s)
  write-cache-ttl: 12h0m0s
    
# es:
#   # The username required by ElasticSearch
#   username: string
#   # The password required by ElasticSearch
#   password: string
#   # The comma-separated list of ElasticSearch servers, must be full url i.e. http://localhost:9200 (default "http://127.0.0.1:9200")
#   server-urls: string
#   # The maximum lookback for spans in ElasticSearch (default 72h0m0s)
#   max-span-age: duration
#   # The number of replicas per index in ElasticSearch (default 1)
#   num-replicas: int
#   # The number of shards per index in ElasticSearch (default 5)
#   num-shards: int
#   # The sniffer config for ElasticSearch; client uses sniffing process to find all nodes automatically, disable if not required
#   sniffer:                               

cassandra:
  # The number of Cassandra connections from a single backend instance (default 2)
  connections-per-host: 2
  # The Cassandra keyspace for Jaeger data (default "jaeger_v1_local")
  keyspace: jaeger_v1_test
  # The number of attempts when reading from Cassandra (default 3)
  max-retry-attempts: 3
  # Username for password authentication for Cassandra
  username: jaeger
  # Password for password authentication for Cassandra
  password: jaeger
  # The port for cassandra
  port: 9042
  # The Cassandra protocol version (default 4)
  proto-version: 4
  # The comma-separated list of Cassandra servers (default "127.0.0.1")
  servers: cassandra
  # Cassandra's keepalive period to use, enabled if > 0 (default 0s)
  socket-keep-alive: 0s
  # Timeout used for queries (default 0s)
  timeout: 0s
  # Enable TLS
  tls: false
  # tls:
  #   # Path to TLS CA file
  #   ca: string
  #   # Path to TLS certificate file
  #   cert: string
  #   # Path to TLS key file
  #   key: string
  #   # Override the TLS server name
  #   server-name: string
  #   # Enable (or disable) host key verification
  #   verify-host:    
    