# Component configs
component-name: flaki-service
component-http-address: 0.0.0.0:8888
component-grpc-address: 0.0.0.0:5555

# Flaki generator configs
flaki-node-id: 0
flaki-component-id: 0

# Influx DB configs
influx-url: influx
influx-username: flaki
influx-password: flaki
influx-database: flaki
influx-precision: s
influx-retention-policy: ""
influx-write-consistency: ""
influx-write-interval-ms: 1000

# Sentry configs
sentry-dsn: http://8f631fb132c9485a93f5e2a1fe577a8c:88a294d696104a97ba26fc673b5288bf@sentry:80/2

# Jaeger configs
jaeger-sampler-type: const
jaeger-sampler-param: 1
jaeger-sampler-url: 127.0.0.1:5775
jaeger-reporter-logspan: false
jaeger-reporter-flushinterval-ms: 1000
