#Global
dynamic_keys: True

git_tag: initial
git_repo: git@github.com:cloudtrust/ceph-service.git
ceph_tools_git_tag: initial
config_repo: git@github.com:cloudtrust/dev-config.git
config_git_tag: ceph-test
